kraken:
    kubeconfig_path: /home/sivakrishnavemuri91/.kube/config                    # Path to kubeconfig
    exit_on_failure: False                                 # Exit when a post action scenario fails
    chaos_scenarios:                                         # List of policies/chaos scenarios to load
        -   pod_scenarios:                                 # List of chaos pod scenarios to load
              - -    scenarios/regex_openshift_pod_kill.yml
          #    - -    https://raw.githubusercontent.com/siva2krish/kraken/master/scenarios/regex_openshift_pod_kill.yml
cerberus:
    cerberus_enabled: true                                # Enable it when cerberus is previously instal
    cerberus_url: http://52.224.144.215:8080/             # When cerberus_enabled is set to True, provide the url where cerberus publishes go/no-go

tunings:
    wait_duration: 60                                      # Duration to wait between each chaos scenario
    iterations: 1                                          # Number of times to execute the scenarios
    daemon_mode: True                                     # Iterations are set to infinity which means that the kraken will cause chaos foreve
